### ISSUE TITLE
doesnt show up in the hb launcher

### ISSUE THREAD

**Issue by KPGC-YT** [fortheusers/hb-appstore#101] opened 2023-04-23 16:21 UTC
i cant find the hb store in the hb launcher
does someone know why?

**Comment by vgmoose** [comment] 2023-04-23 18:52
On Wii U? What's your setup? Most likely this is caused by an outdated HBL that doesn't support RPX files.

**Comment by vgmoose** [comment] 2023-07-05 00:07
Closing this issue, but can re-open if there's something else going on. Just make sure the RPX file is in `sd:/wiiu/apps/appstore` and that the latest HBL is being used (older ones only supported ELF files)

**Closed by vgmoose** 2023-07-05 00:07 UTC
